framework:
    secret: '%env(FORMVEX_SPOKE_APP_SECRET)%'
    handle_all_throwables: true
    http_method_override: false
    router:
        utf8: true
    php_errors:
        log: true

when@test:
    framework:
        test: true
